# Simulating Coin Flips
**check this documentation https://numpy.org/doc/stable/reference/random/index.html To Know how to use Random sampling**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
# outcome of one coin flip
np.random.randint(2)

1

In [13]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([1, 0, 1, ..., 1, 0, 0])

In [16]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10).mean()

0.6

In [19]:
# outcome of one coin flip
np.random.choice([0, 1])

0

In [18]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([1, 1, 0, ..., 1, 1, 1])

In [23]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.4958

In [24]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([0, 0, 0, ..., 0, 1, 0])

In [27]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.1993